package com.test.spring.domain.entity;

import java.util.Date;

public class MemberEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_ID
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_NAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_NICKNAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.BIRTH_DATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private Date birthDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_EMAIL
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_PHONE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String memberPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.LICENSE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String license;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_REGDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private Date memberRegdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.MEMBER_UPDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private Date memberUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEMBER.ENABLED
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    private String enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_ID
     *
     * @return the value of MEMBER.MEMBER_ID
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_ID
     *
     * @param memberId the value for MEMBER.MEMBER_ID
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_PASSWORD
     *
     * @return the value of MEMBER.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberPassword() {
        return memberPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_PASSWORD
     *
     * @param memberPassword the value for MEMBER.MEMBER_PASSWORD
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberPassword(String memberPassword) {
        this.memberPassword = memberPassword == null ? null : memberPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_NAME
     *
     * @return the value of MEMBER.MEMBER_NAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_NAME
     *
     * @param memberName the value for MEMBER.MEMBER_NAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_NICKNAME
     *
     * @return the value of MEMBER.MEMBER_NICKNAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberNickname() {
        return memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_NICKNAME
     *
     * @param memberNickname the value for MEMBER.MEMBER_NICKNAME
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberNickname(String memberNickname) {
        this.memberNickname = memberNickname == null ? null : memberNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.BIRTH_DATE
     *
     * @return the value of MEMBER.BIRTH_DATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.BIRTH_DATE
     *
     * @param birthDate the value for MEMBER.BIRTH_DATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_EMAIL
     *
     * @return the value of MEMBER.MEMBER_EMAIL
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberEmail() {
        return memberEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_EMAIL
     *
     * @param memberEmail the value for MEMBER.MEMBER_EMAIL
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberEmail(String memberEmail) {
        this.memberEmail = memberEmail == null ? null : memberEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_PHONE
     *
     * @return the value of MEMBER.MEMBER_PHONE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getMemberPhone() {
        return memberPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_PHONE
     *
     * @param memberPhone the value for MEMBER.MEMBER_PHONE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberPhone(String memberPhone) {
        this.memberPhone = memberPhone == null ? null : memberPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.LICENSE
     *
     * @return the value of MEMBER.LICENSE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.LICENSE
     *
     * @param license the value for MEMBER.LICENSE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_REGDATE
     *
     * @return the value of MEMBER.MEMBER_REGDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public Date getMemberRegdate() {
        return memberRegdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_REGDATE
     *
     * @param memberRegdate the value for MEMBER.MEMBER_REGDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberRegdate(Date memberRegdate) {
        this.memberRegdate = memberRegdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.MEMBER_UPDATE
     *
     * @return the value of MEMBER.MEMBER_UPDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public Date getMemberUpdate() {
        return memberUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.MEMBER_UPDATE
     *
     * @param memberUpdate the value for MEMBER.MEMBER_UPDATE
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setMemberUpdate(Date memberUpdate) {
        this.memberUpdate = memberUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEMBER.ENABLED
     *
     * @return the value of MEMBER.ENABLED
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEMBER.ENABLED
     *
     * @param enabled the value for MEMBER.ENABLED
     *
     * @mbg.generated Thu Mar 18 22:27:47 KST 2021
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }
}