package com.test.spring.domain;

public class Countries {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRIES.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRIES.COUNTRY_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNTRIES.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short regionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES.COUNTRY_ID
     *
     * @return the value of COUNTRIES.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES.COUNTRY_ID
     *
     * @param countryId the value for COUNTRIES.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES.COUNTRY_NAME
     *
     * @return the value of COUNTRIES.COUNTRY_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES.COUNTRY_NAME
     *
     * @param countryName the value for COUNTRIES.COUNTRY_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNTRIES.REGION_ID
     *
     * @return the value of COUNTRIES.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNTRIES.REGION_ID
     *
     * @param regionId the value for COUNTRIES.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setRegionId(Short regionId) {
        this.regionId = regionId;
    }
}