package com.test.spring.domain;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String departmentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short locationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @return the value of DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DEPARTMENT_ID
     *
     * @param departmentId the value for DEPARTMENTS.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @return the value of DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.DEPARTMENT_NAME
     *
     * @param departmentName the value for DEPARTMENTS.DEPARTMENT_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.MANAGER_ID
     *
     * @return the value of DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.MANAGER_ID
     *
     * @param managerId the value for DEPARTMENTS.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENTS.LOCATION_ID
     *
     * @return the value of DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENTS.LOCATION_ID
     *
     * @param locationId the value for DEPARTMENTS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setLocationId(Short locationId) {
        this.locationId = locationId;
    }
}