package com.test.spring.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.EMAIL
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Date hireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private BigDecimal salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private BigDecimal commissionPct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @return the value of EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.EMPLOYEE_ID
     *
     * @param employeeId the value for EMPLOYEES.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.FIRST_NAME
     *
     * @return the value of EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.FIRST_NAME
     *
     * @param firstName the value for EMPLOYEES.FIRST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.LAST_NAME
     *
     * @return the value of EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.LAST_NAME
     *
     * @param lastName the value for EMPLOYEES.LAST_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.EMAIL
     *
     * @return the value of EMPLOYEES.EMAIL
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.EMAIL
     *
     * @param email the value for EMPLOYEES.EMAIL
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.PHONE_NUMBER
     *
     * @return the value of EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.PHONE_NUMBER
     *
     * @param phoneNumber the value for EMPLOYEES.PHONE_NUMBER
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.HIRE_DATE
     *
     * @return the value of EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Date getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.HIRE_DATE
     *
     * @param hireDate the value for EMPLOYEES.HIRE_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.JOB_ID
     *
     * @return the value of EMPLOYEES.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.JOB_ID
     *
     * @param jobId the value for EMPLOYEES.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.SALARY
     *
     * @return the value of EMPLOYEES.SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.SALARY
     *
     * @param salary the value for EMPLOYEES.SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.COMMISSION_PCT
     *
     * @return the value of EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public BigDecimal getCommissionPct() {
        return commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.COMMISSION_PCT
     *
     * @param commissionPct the value for EMPLOYEES.COMMISSION_PCT
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setCommissionPct(BigDecimal commissionPct) {
        this.commissionPct = commissionPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.MANAGER_ID
     *
     * @return the value of EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.MANAGER_ID
     *
     * @param managerId the value for EMPLOYEES.MANAGER_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @return the value of EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMPLOYEES.DEPARTMENT_ID
     *
     * @param departmentId the value for EMPLOYEES.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }
}