package com.test.spring.domain;

import java.util.Date;

public class JobHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.START_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.END_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOB_HISTORY.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @return the value of JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.EMPLOYEE_ID
     *
     * @param employeeId the value for JOB_HISTORY.EMPLOYEE_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.START_DATE
     *
     * @return the value of JOB_HISTORY.START_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.START_DATE
     *
     * @param startDate the value for JOB_HISTORY.START_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.END_DATE
     *
     * @return the value of JOB_HISTORY.END_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.END_DATE
     *
     * @param endDate the value for JOB_HISTORY.END_DATE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.JOB_ID
     *
     * @return the value of JOB_HISTORY.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.JOB_ID
     *
     * @param jobId the value for JOB_HISTORY.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOB_HISTORY.DEPARTMENT_ID
     *
     * @return the value of JOB_HISTORY.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOB_HISTORY.DEPARTMENT_ID
     *
     * @param departmentId the value for JOB_HISTORY.DEPARTMENT_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setDepartmentId(Short departmentId) {
        this.departmentId = departmentId;
    }
}