package com.test.spring.domain;

public class Jobs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.JOB_TITLE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String jobTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.MIN_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer minSalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JOBS.MAX_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Integer maxSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.JOB_ID
     *
     * @return the value of JOBS.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.JOB_ID
     *
     * @param jobId the value for JOBS.JOB_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.JOB_TITLE
     *
     * @return the value of JOBS.JOB_TITLE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.JOB_TITLE
     *
     * @param jobTitle the value for JOBS.JOB_TITLE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle == null ? null : jobTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.MIN_SALARY
     *
     * @return the value of JOBS.MIN_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getMinSalary() {
        return minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.MIN_SALARY
     *
     * @param minSalary the value for JOBS.MIN_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setMinSalary(Integer minSalary) {
        this.minSalary = minSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JOBS.MAX_SALARY
     *
     * @return the value of JOBS.MAX_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Integer getMaxSalary() {
        return maxSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JOBS.MAX_SALARY
     *
     * @param maxSalary the value for JOBS.MAX_SALARY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setMaxSalary(Integer maxSalary) {
        this.maxSalary = maxSalary;
    }
}