package com.test.spring.domain;

public class Locations {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.STREET_ADDRESS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String streetAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.POSTAL_CODE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.CITY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.STATE_PROVINCE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String stateProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOCATIONS.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String countryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.LOCATION_ID
     *
     * @return the value of LOCATIONS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.LOCATION_ID
     *
     * @param locationId the value for LOCATIONS.LOCATION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setLocationId(Short locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.STREET_ADDRESS
     *
     * @return the value of LOCATIONS.STREET_ADDRESS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.STREET_ADDRESS
     *
     * @param streetAddress the value for LOCATIONS.STREET_ADDRESS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress == null ? null : streetAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.POSTAL_CODE
     *
     * @return the value of LOCATIONS.POSTAL_CODE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.POSTAL_CODE
     *
     * @param postalCode the value for LOCATIONS.POSTAL_CODE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.CITY
     *
     * @return the value of LOCATIONS.CITY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.CITY
     *
     * @param city the value for LOCATIONS.CITY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.STATE_PROVINCE
     *
     * @return the value of LOCATIONS.STATE_PROVINCE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getStateProvince() {
        return stateProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.STATE_PROVINCE
     *
     * @param stateProvince the value for LOCATIONS.STATE_PROVINCE
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince == null ? null : stateProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOCATIONS.COUNTRY_ID
     *
     * @return the value of LOCATIONS.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOCATIONS.COUNTRY_ID
     *
     * @param countryId the value for LOCATIONS.COUNTRY_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }
}