package com.test.spring.domain;

public class Regions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGIONS.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private Short regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REGIONS.REGION_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    private String regionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGIONS.REGION_ID
     *
     * @return the value of REGIONS.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public Short getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGIONS.REGION_ID
     *
     * @param regionId the value for REGIONS.REGION_ID
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setRegionId(Short regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REGIONS.REGION_NAME
     *
     * @return the value of REGIONS.REGION_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REGIONS.REGION_NAME
     *
     * @param regionName the value for REGIONS.REGION_NAME
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }
}