package com.test.spring.mapper;

import com.test.spring.domain.Departments;
import java.util.List;

public interface DepartmentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int deleteByPrimaryKey(Short departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int insert(Departments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    Departments selectByPrimaryKey(Short departmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    List<Departments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENTS
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int updateByPrimaryKey(Departments record);
}