package com.test.spring.mapper;

import com.test.spring.domain.JobHistory;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int deleteByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("startDate") Date startDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int insert(JobHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    JobHistory selectByPrimaryKey(@Param("employeeId") Integer employeeId, @Param("startDate") Date startDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    List<JobHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JOB_HISTORY
     *
     * @mbg.generated Sat Mar 13 20:21:58 KST 2021
     */
    int updateByPrimaryKey(JobHistory record);
}